[project]
name = "custom-mcp-server"
version = "0.1.0"
description = "custom-mcp-server for Claude desktop app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
]
